name: Clean GH-PAGES

# on pull_request -> closed
on: [workflow_dispatch]

jobs:
  clean:
    # [self-hosted, linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # checkout specific branch
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          rm -rf 'delete-me copy'
          git add .
          git commit -m "deleted dummy dir"
          git push
